name: Feature request
description: Request the addition of a new bug example
title: '[Bug feature]: '
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the related request.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Error message
      description: If any, provide the related error message
  - type: input
    attributes:
      label: Stackblitz reproduction link
      description: >-
        Provide a example showcasing the error in a simple context
        (https://stackblitz.com/)
  - type: dropdown
    attributes:
      label: I would like to make a pull request for this feature
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
